In [2]:
import pandas as pd
import numpy as np

In [3]:
reviews = pd.read_csv("Reviews.csv")

In [4]:
df = reviews.copy()

In [5]:
df.head()

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...  
2  "Delight" says it all  This is a confection that has been around a fe...  
3         Cough Medicine  If you are looking for the secret ingredient i...  
4            Great taffy  Great taffy at a great price.  There was a wid...

In [6]:
df.isnull().sum()

Id                         0
ProductId                  0
UserId                     0
ProfileName               16
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   27
Text                       0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype 
---  ------                  --------------   ----- 
 0   Id                      568454 non-null  int64 
 1   ProductId               568454 non-null  object
 2   UserId                  568454 non-null  object
 3   ProfileName             568438 non-null  object
 4   HelpfulnessNumerator    568454 non-null  int64 
 5   HelpfulnessDenominator  568454 non-null  int64 
 6   Score                   568454 non-null  int64 
 7   Time                    568454 non-null  int64 
 8   Summary                 568427 non-null  object
 9   Text                    568454 non-null  object
dtypes: int64(5), object(5)
memory usage: 43.4+ MB


In [8]:
df["ProfileName"] = df["ProfileName"].fillna(df["ProfileName"].mode()[0])
df["Summary"] = df["Summary"].fillna(df["Summary"].mode()[0])


In [9]:
df.isnull().sum()

Id                        0
ProductId                 0
UserId                    0
ProfileName               0
HelpfulnessNumerator      0
HelpfulnessDenominator    0
Score                     0
Time                      0
Summary                   0
Text                      0
dtype: int64

In [10]:
df.groupby("Score").sum()

Id  HelpfulnessNumerator  HelpfulnessDenominator  \
Score                                                               
1       14754231438                142964                  254536   
2        8358480873                 55341                   92365   
3       11924089130                 72529                  105167   
4       22721582873                112134                  134378   
5      103811874971                608312                  680530   

                  Time  
Score                   
1       68113540224000  
2       38733367795200  
3       55437391958400  
4      104587119388800  
5      469990832716800

In [11]:
df["Score"].replace(1, value="negatif",inplace = True )
df["Score"].replace(2, value="negatif",inplace = True )

In [12]:
df["Score"].replace(4, value="positive",inplace = True )
df["Score"].replace(5, value="positive",inplace = True )

In [13]:
df = df[(df.Score== "negatif")| (df.Score == "positive")]

In [14]:
df.groupby("Score").count()

Id  ProductId  UserId  ProfileName  HelpfulnessNumerator  \
Score                                                                    
negatif    82037      82037   82037        82037                 82037   
positive  443777     443777  443777       443777                443777   

          HelpfulnessDenominator    Time  Summary    Text  
Score                                                      
negatif                    82037   82037    82037   82037  
positive                  443777  443777   443777  443777

In [15]:
df_main = pd.DataFrame()

In [16]:
df_main["text"] = df["Text"]
df_main["label"]= df["Score"]

In [17]:
df_main.head()

text     label
0  I have bought several of the Vitality canned d...  positive
1  Product arrived labeled as Jumbo Salted Peanut...   negatif
2  This is a confection that has been around a fe...  positive
3  If you are looking for the secret ingredient i...   negatif
4  Great taffy at a great price.  There was a wid...  positive

In [18]:
#buyuk kucuk donusumu
df_main["text"] = df_main["text"].apply(lambda x: " ".join(x.lower() for x in x.split()))

In [19]:
df_main["text"]

0         i have bought several of the vitality canned d...
1         product arrived labeled as jumbo salted peanut...
2         this is a confection that has been around a fe...
3         if you are looking for the secret ingredient i...
4         great taffy at a great price. there was a wide...
                                ...                        
568449    great for sesame chicken..this is a good if no...
568450    i'm disappointed with the flavor. the chocolat...
568451    these stars are small, so you can give 10-15 o...
568452    these are the best treats for training and rew...
568453    i am very satisfied ,product is as advertised,...
Name: text, Length: 525814, dtype: object

In [20]:
#noktalama isaretleri silinmesi
df_main["text"] = df_main["text"].str.replace("[^\w\s]","")

<ipython-input-20-c85a95fcec22>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df_main["text"] = df_main["text"].str.replace("[^\w\s]","")


In [21]:
#sayilarin temizlenmesi
df_main["text"] = df_main["text"].str.replace("\d","")

<ipython-input-21-8c355602f3e4>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df_main["text"] = df_main["text"].str.replace("\d","")


In [22]:
df_main["text"]

0         i have bought several of the vitality canned d...
1         product arrived labeled as jumbo salted peanut...
2         this is a confection that has been around a fe...
3         if you are looking for the secret ingredient i...
4         great taffy at a great price there was a wide ...
                                ...                        
568449    great for sesame chickenthis is a good if not ...
568450    im disappointed with the flavor the chocolate ...
568451    these stars are small so you can give  of thos...
568452    these are the best treats for training and rew...
568453    i am very satisfied product is as advertised i...
Name: text, Length: 525814, dtype: object

In [23]:
import nltk 
nltk.download("stopwords")
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/halime/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [24]:
#STOPWORDS
sw = stopwords.words("english")
df_main["text"] = df_main["text"].apply(lambda x: " ".join(x for x in x.split() if x not in sw))

In [25]:
#az gecen kelimelerin silinmesi
sil = pd.Series(" ".join(df_main["text"]).split()).value_counts()[-1000:]
df_main["text"] = df_main["text"].apply(lambda x: " ".join(x for x in x.split() if x not in sil))

In [26]:
#lemmatization
from textblob import Word
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to /Users/halime/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [27]:
df_main["text"] = df_main["text"].apply(lambda x:" ".join([Word(word).lemmatize() for word in x.split()]))

In [28]:
df_main.head()

text     label
0  bought several vitality canned dog food produc...  positive
1  product arrived labeled jumbo salted peanutsth...   negatif
2  confection around century light pillowy citrus...  positive
3  looking secret ingredient robitussin believe f...   negatif
4  great taffy great price wide assortment yummy ...  positive

#TEST-TRAIN SPLITTING 

In [29]:
from sklearn.model_selection import train_test_split
train_x, test_x,train_y,test_y = train_test_split(df_main["text"],df_main["label"])

In [30]:
train_x.head()

444660    absolute favorite tea always keep kitchen stoc...
334339    first batch purchased ant embedded toffee seco...
367851    love coconut oil best makeup remover ever yes ...
211168    buy wellness cat try give variety ive tried fl...
121845    rich complex coffee blend truly bold flavor wi...
Name: text, dtype: object

In [31]:
from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()

In [32]:
from sklearn.preprocessing import StandardScaler
train_y = encoder.fit_transform(train_y)
test_y = encoder.fit_transform(test_y)

In [33]:
train_y[0:5]

array([1, 0, 1, 1, 1])

In [34]:
test_y[0:5]

array([1, 1, 1, 1, 1])

#COUNT VECTORS

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer.fit(train_x)

CountVectorizer()

In [36]:
X_train_count = vectorizer.transform(train_x)
X_test_count = vectorizer.transform(test_x)

In [37]:
vectorizer.get_feature_names()[0:10]

['__',
 '___',
 '____',
 '_____',
 '______',
 '_______',
 '________',
 '__________',
 '___________',
 '________________________________________']

In [38]:
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#TF-IDF 

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf_word_vectorizer = TfidfVectorizer()
tf_idf_word_vectorizer.fit(train_x)

TfidfVectorizer()

In [42]:
X_train_tf_idf_word = tf_idf_word_vectorizer.transform(train_x)
X_test_tf_idf_word = tf_idf_word_vectorizer.transform(test_x)

In [39]:
#LOGISTIC REGRESSION

In [46]:
from sklearn.linear_model import LogisticRegression


In [50]:
loj = LogisticRegression()

In [51]:
loj_model = loj.fit(X_train_count,train_y)

/Users/halime/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [53]:
from sklearn.model_selection import cross_val_score


In [54]:
accuracy = cross_val_score(loj_model, X_test_count,test_y, cv=10).mean()

/Users/halime/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/halime/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#log

In [55]:
print(accuracy)

0.9315121139727125


In [104]:
texts = df_main["text"]

In [105]:
yeni_yorum = pd.Series(texts)

In [106]:
v = CountVectorizer()
v.fit(train_x)
yeni_yorum = v.transform(yeni_yorum)

In [107]:
sentiment = loj_model.predict(yeni_yorum)

In [113]:
sentiment[0:100]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [88]:
reviews.head()

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...  
2  "Delight" says it all  This is a confection that has been around a fe...  
3         Cough Medicine  If you are looking for the secret ingredient i...  
4            Great taffy  Great taffy at a great price.  There was a wid...

In [94]:
y = df_main["label"]

In [114]:
y[0:100]

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [95]:
y = encoder.fit_transform(y)

In [91]:
from sklearn.metrics import confusion_matrix


In [109]:
from sklearn.metrics import accuracy_score

accuracy_score(y,sentiment)

0.948510309729296